proj_setup <- function(path, ...) {

  # Create directories
  dir.create(path, recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/Pings"), recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/EVTemplate"), recursive = TRUE, showWarnings = FALSE)

  # create some header text
  header <- c(
    "# Erie Acoustic Project",
    "*project template generated by* `erieacoustics`"
  )

  instructions <- c(
    "# Erie Acoustic Project Template Intructions",
    "## Folder Description and Contents",
    "File | Description",
    "---------- | --------------------------------------------------",
    "Pings | contains the acoustic data for each transect",
    "Pings/TransectName | each transect should be uniquely named and all data stored within a single directory",
    "EVTemplate | Echoview processing templates should be stored here to be available to `set_up_transect`",
    "### *This file can be deleted following project set up.*"
  )

  writeLines(instructions, con = file.path(path, "Instructions.md"))

  # collect inputs and paste together as 'Parameter: Value'
  dots <- list(...)
  text <- lapply(seq_along(dots), function(i) {
    key <- names(dots)[[i]]
    val <- dots[[i]]
    paste0(key, ": ", val)
  })

  # collect into single text string
  contents <- paste(
    paste(header, collapse = "\n"),
    paste(text, collapse = "\n"),
    sep = "  \n"
  )

  # write to index file
  writeLines(contents, con = file.path(path, "ReadMe.md"))
}
