proj_setup <- function(path, ...) {

  # Create directories
  dir.create(path, recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/1_Annual_Protocol"), recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/2_EVTemplate"), recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/3_Ping_Data"), recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/4_Trawl_Data"), recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/5_Enviro_Data"), recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/6_Misc"), recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, "/7_Annual_Summary"), recursive = TRUE, showWarnings = FALSE)

  # create some header text
  header <- c(
    "# Erie Acoustic Project",
    "*project template generated by* `erieacoustics`"
   )

  filetable <- c(
    "## Folder Description and Contents",
    "File | Description",
    "---------- | --------------------------------------------------",
    "1_Annual_Protocol | contains Rmarkdown scripts and products for annual survey protocol",
    "2_EVTemplate | Echoview processing template should be stored here to be available to `set_up_transect`",
    "3_Ping_Data | contains the acoustic data for each transect",
    "3_Ping_Data/TransectName | each transect should be uniquely named and all data stored within a single directory",
    "4_Trawl_Data | contains the paired trawl data",
    "5_Enviro_Data | contains environmental measurements",
    "6_Misc | contains miscellaneous files associated with survey",
    "7_Annual_Summary | contains Rmarkdown scripts and products for annual summary"
  )

  instructions <- c(
    "# Erie Acoustic Project Template Intructions  ",
    "This file is best viewed by using the *PREVIEW* feature in RStudio  ",
    "### *This file can be deleted following project set up.*  ",
    " ",
    "## What's included  ",
    "1. README.md template  ",
    "2. Instructions.md  ",
    "3. A gitignore file has been included. If you have git installed you will still need to run `git init` to initialize the repo.  ",
    "4. Template folder directory has been created. This directory structure is required for certain funtions to run as intended.  ",
    "5. Example analysis scripts have been included to assist in utilizing built in functions.  ",
    "  ",
    "## Instructions  ",
    "1. Please review and update the README.md file.  ",
    "2. In RStudio, running 'Preview' will knit the md file to create an html README file.  ",
    "3. Each transect's data should be in individual folders within 3_Ping_Data.  ",
    "4. The analysis template should be copied to 2_EVTemplate  ",
    "  ",
    "## Processing Steps  ",
    "1. Analyze the calibration data first as the *.ecs file is required in the current template.  ",
    "2. Open the EV template and edit the template to include the new calibration file. Save as a new template in 2_EVTemplate.  ",
    "3. Open and edit `1_run_setup_template.R`. This script applies the custom set up functions from `erieacoustics` to apply COM commands directly to Echoview to import and save a new EV file.  ",
    "4. Run `1_run_setup_template.R`. *WARNING*: this process could take a long time!   ",
    "5. Inspect and edit each transect EV file. See *link to detailed instructions*  ",
    "6. When data inspection and editing is complete, run `2_Export_EVdata.r` to export each transect. *WARNING*: this could take a long time.  ",
    "7. Open `3_Biomass_Analysis.r` and edit as required to complete the data analysis.  "
  )


  writeLines(c(instructions, " ", filetable), con = file.path(path, "Instructions.md"))

  # collect inputs and paste together as 'Parameter: Value'
  dots <- list(...)
  text <- lapply(seq_along(dots), function(i) {
    key <- names(dots)[[i]]
    val <- dots[[i]]
    paste0(key, ": ", val, "<br />")
  })

  # collect into single text string
  contents <- paste(
    paste(header, collapse = "\n"),
    paste(text, collapse = "\n"),
    sep = "  \n"
  )

  abstract <-  c(
    "# Abstract",
    " ",
    "Please provide a simple description of the project"
  )

  # write to index file
  readme <- c(contents, " ", abstract, " ", filetable)
  writeLines(readme, con = file.path(path, "ReadMe.md"))

  # write gitignore file
  gitignore <- c(
    "# Gitignore file autogenerated by `erieacoustics`",
    ".Rproj.user",
    ".Rhistory",
    ".RData",
    ".Ruserdata",
    "*.html",
    "",
    "# Acoustic file types",
    "*.bot",
    "*.raw",
    "*.idx",
    "*.evi",
    "*.evwx",
    "*.evb",
    "*.dt4",
    "*.rtp",
    "*.rtpx",
    "*.dg"
  )

  writeLines(gitignore, con = file.path(path, ".gitignore"))

  transect_setup <- c(
    "# Export transect data",
    "library(erieacoustics)",
    "# Edit the template file name:",
    "templatefile <- '2_EVTemplate/ErieHacTemplate_2021_v2_simrad.EV'",
    "evtemplate <- file.path(getwd(), templatefile)",
    "dir.exists('3_Ping_Data')",
    "file.exists(evtemplate)",
    "",
    "transects <- dir('3_Ping_Data')",
    "",
    "# run all",
    "# Edit TRANSDUCER type:",
    "TRANSDUCER <- 'SIMRAD'",
    "run_all <- function(x) {set_up_transect(evtemplate, getwd(), TRANSDUCER, x)}",
    "lapply(transects, run_all)"
  )

  writeLines(transect_setup, con = file.path(path, "7_Annual_Summary/1_run_setup_template.R"))
}
